addSbtPlugin("io.spray"         % "sbt-revolver"        % "0.9.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.0")
addSbtPlugin("org.xerial.sbt"   % "sbt-sonatype"        % "3.9.10")
addSbtPlugin("com.github.sbt"   % "sbt-pgp"             % "2.1.2")
addSbtPlugin("com.typesafe.sbt" % "sbt-git"             % "1.0.1")
addSbtPlugin("com.eed3si9n"     % "sbt-buildinfo"       % "0.10.0")
addSbtPlugin("com.codecommit"   % "sbt-github-actions"  % "0.13.0")
addSbtPlugin("org.scalameta"    % "sbt-scalafmt"        % "2.4.3")
